Update Activity to include day
nitobuendia/oura-custom-component pull request #39
Opened 2023-12-07 18:33 UTC by maco2035

This is adding the day to the Activity sensor attributes, It helps to prevent issues that I encountered from the day not showing up by default compared to other sensors. fixes #38

2023-12-11 12:33 UTC, nitobuendia requested changes
The code changes look good. Thanks for making these. I have added a small comment on each file, then we can merge :)

2023-12-11 12:33 UTC, nitobuendia commented on README.md
> +By default, the following attributes are being monitored: `active_calories`, `high_activity_time`, `low_activity_time`, `medium_activity_time`, `non_wear_time`, `resting_time`, `sedentary_time`, `sco
nit: The attributes are alphabetically ordered. Do you mind putting `day` between `active_calories` and `high_activity_time`?

2023-12-11 12:33 UTC, nitobuendia commented on custom_components/oura/sensor_activity.py
> +    'day',
nit: The attributes are alphabetically ordered. Do you mind putting 'day' between 'active_calories' and 'high_activity_time'?

2023-12-14 07:59 UTC, maco2035 commented
@nitobuendia Thanks for reviewing my PR, and making this cool integration!

2023-12-14 09:36 UTC, nitobuendia approved these changes
One of the changes was not done, but approving as it's on the docs.

2023-12-14 09:36 UTC, nitobuendia commented on README.md
> +By default, the following attributes are being monitored: `active_calories`, `high_activity_time`, `low_activity_time`, `medium_activity_time`, `non_wear_time`, `resting_time`, `sedentary_time`, `sco
This was changed only for sensor_activity.py and not for `README`.

2023-12-14 09:36 UTC, merged